"""Inicial

Revision ID: 8d451fc39f80
Revises: 
Create Date: 2023-09-19 12:59:34.431536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d451fc39f80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_book',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('criacao_dt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lancamento_dt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cash_book')
    # ### end Alembic commands ###
